openapi: 3.0.1
info:
  title: pagopa-arc-be
  description: Api and Models
  version: 0.0.1
servers:
  - url: 'https://${hostname}/arc/v1'
paths:
  /transactions:
    get:
      tags:
        - arc transactions
      summary: Retrieve the paged transaction list from arc
      operationId: getTransactionsList
      parameters:
        - name: page
          in: query
          description: Number of page required
          required: false
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          description: Number of items for page
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: filter
          in: query
          description: The field passed to filter the list of transactions
          required: false
          schema:
            type: string
            enum: [payedByMe, registeredToMe]
          example: payedByMe
      responses:
        '200':
          description: Obtained transaction list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsListDTO'
        '401':
          description: Wrong or missing function key
        '429':
          description: Too many Requests
        '500':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /transactions/{transactionId}:
    get:
      tags:
        - arc transactions
      summary: Retrieve transaction details from arc
      operationId: getTransactionDetails
      parameters:
        - name: transactionId
          in: path
          description: A unique id that identifies a transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Obtained transaction details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetailsDTO'
        '401':
          description: Wrong or missing function key
        '404':
          description: Transaction details not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                error: transaction_not_found_error
                error_description: "string"
        '429':
          description: Too many Requests
        '500':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /transactions/{transactionId}/receipt:
    get:
      tags:
        - arc transactions
      summary: Retrieve transaction receipt from arc
      operationId: getTransactionReceipt
      parameters:
        - name: transactionId
          in: path
          description: A unique id that identifies a transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Obtained PDF transaction receipt
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '401':
          description: Wrong or missing function key
        '404':
          description: Transaction details not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
              example:
                error: receipt_not_found_error
                error_description: "string"
        '429':
          description: Too many Requests
        '500':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    TransactionsListDTO:
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionDTO'
        currentPage:
          type: integer
          format: int32
        itemsForPage:
          type: integer
          format: int32
        totalItems:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
    TransactionDTO:
      type: object
      properties:
        transactionId:
          type: string
        payeeName:
          type: string
        payeeTaxCode:
          type: string
        amount:
          type: integer
          format: int64
        transactionDate:
          type: string
          format: date-time
          example: '2024-05-31T13:07:25Z'
        isCart:
          type: boolean
        payedByMe:
          type: boolean
        registeredToMe:
          type: boolean
    TransactionDetailsDTO:
      type: object
      properties:
        infoTransaction:
          $ref: '#/components/schemas/InfoTransactionDTO'
        carts:
          type: array
          items:
            $ref: '#/components/schemas/CartItemDTO'
    InfoTransactionDTO:
      type: object
      properties:
        transactionId:
          type: string
        authCode:
          type: string
        rrn:
          type: string
        transactionDate:
          type: string
          format: date-time
          example: '2024-05-31T13:07:25Z'
        pspName:
          type: string
        walletInfo:
          $ref: '#/components/schemas/WalletInfoDTO'
        paymentMethod:
          type: string
          enum:
            - BBT
            - BP
            - AD
            - CP
            - PO
            - OBEP
            - JIF
            - MYBK
            - PPAL
            - UNKNOWN
        payer:
          $ref: '#/components/schemas/UserDetailDTO'
        amount:
          type: integer
          format: int64
        fee:
          type: integer
          format: int64
        origin:
          type: string
          enum:
            - INTERNAL
            - PM
            - NDP001PROD
            - NDP002PROD
            - NDP003PROD
            - UNKNOWN
    CartItemDTO:
      type: object
      properties:
        subject:
          type: string
        amount:
          type: integer
          format: int64
        payee:
          $ref: '#/components/schemas/UserDetailDTO'
        debtor:
          $ref: '#/components/schemas/UserDetailDTO'
        refNumberValue:
          type: string
        refNumberType:
          type: string
    UserDetailDTO:
      type: object
      properties:
        name:
          type: string
        taxCode:
          type: string
    WalletInfoDTO:
      type: object
      properties:
        accountHolder:
          type: string
        brand:
          type: string
        blurredNumber:
          type: string
        maskedEmail:
          type: string
    ErrorDTO:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          enum:
            - generic_error
            - transaction_not_found_error
            - receipt_not_found_error
            - invalid_amount
            - invalid_date
            - invalid_request
        error_description:
          type: string
          x-field-extra-annotation: '@com.fasterxml.jackson.annotation.JsonProperty("error_description")'
