openapi: 3.0.1
info:
  title: pagopa-arc-be
  description: Api and Models
  version: 0.0.1
servers:
  - url: 'https://${hostname}/health/v1'
paths:
  /status:
    get:
      tags:
        - health
      summary: "Provides application liveliness, including redis"
      operationId: getHealthLiveness
      responses:
        '200':
          description: "Obtained health status"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthLivenessResponse'
        '503':
          description: "Service unavailable"
components:
  schemas:
    HealthLivenessResponse:
      type: object
      properties:
        status:
          allOf:
            - $ref: '#/components/schemas/HealthStatus'
            - description: Overall status of the application
        components:
          type: object
          properties:
            diskSpace:
              type: object
              properties:
                status:
                  allOf:
                    - $ref: '#/components/schemas/HealthStatus'
                    - description: Status of disk space
            livenessState:
              type: object
              properties:
                status:
                  allOf:
                    - $ref: '#/components/schemas/HealthStatus'
                    - description: Liveness state status
            redis:
              type: object
              properties:
                status:
                  allOf:
                    - $ref: '#/components/schemas/HealthStatus'
                    - description: Redis connection status
    HealthStatus:
      type: string
      enum:
        - UP
        - UNKNOWN
        - DOWN
        - OUT_OF_SERVICE