name: Validate PR title
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-22.04
    steps:
      - uses: Slashgear/action-check-pr-title@860e8dc639f8e60335a6f5e8936ba67ed2536890 # v4.3.0
        with:
          regexp: '(feat|fix|chore|breaking): \[P4ADEV(-[0-9]{2,4})?\] .+'
          helpMessage: "Example: 'feat: [P4ADEV-41] example of title'"